ALTER TABLE "alert_settings"
  ADD COLUMN IF NOT EXISTS "enable_shadow"      BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "shadow_blur"        INTEGER NOT NULL DEFAULT 20,
  ADD COLUMN IF NOT EXISTS "shadow_color"       TEXT    NOT NULL DEFAULT '#000000',
  ADD COLUMN IF NOT EXISTS "shadow_opacity"     INTEGER NOT NULL DEFAULT 30,
  ADD COLUMN IF NOT EXISTS "shadow_offset_x"    INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "shadow_offset_y"    INTEGER NOT NULL DEFAULT 8,
  ADD COLUMN IF NOT EXISTS "enable_gradient_bg" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "enable_coin_sound"  BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS "coin_sound_volume"  INTEGER NOT NULL DEFAULT 50,
  ADD COLUMN IF NOT EXISTS "tts_sound_delay"    INTEGER NOT NULL DEFAULT 1;
